remote_theme: pmarsceill/just-the-docs 

layout: default

title: Qiskit Virtual Event Planning Guide

search_enabled: false

heading_anchors: true

color_scheme: nil

nav: "_docs/navigation_structure.md"
