remote_theme: pmarsceill/just-the-docs 

title: Qiskit Virtual Event Planning Guide

description: Take your events to the virtual space with tips and tricks from the Qiskit Community Team!

baseurl: "/virtual-event-guide"

search_enabled: false

heading_anchors: true

color_scheme: nil
    
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
