theme: jekyll-theme-slate
title: Hello Qiskitters!
description: This is the Qiskit Virtual Event Planning Guide. This guide is meant as a companion for anyone looking to host a digital event, including resources, templates, and ideas. With that said, most things you’ll find here are suggestions. At the end of the day, you know your audience better than we do. We’re here to help you make it as successful as possible, whatever you chose to do. If you only have a few minutes to read this document, skip to the TL;DR section at the end.

