remote_theme: pmarsceill/just-the-docs 
description: Take your events to the virtual space with tips and tricks from the Qiskit Community Team!
search_enabled: false
heading_anchors: true
color_scheme: nil

layout: default
title: Qiskit Virtual Event Planning Guide
nav_order: 1

#Navigation Structure
{: .no_toc }
